### ISSUE TITLE
[BE] mysql 컨테이너 스키마 초기화문제

### ISSUE THREAD

**Issue by yonghwankim-dev** [yonghwankim-dev/kiosk-max#2]
### 배경
- docker-compose 수행시 mysql 컨테이너를 다음과 같이 설정하였습니다.

```
  db:
    container_name: kiosk_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d
```
- volumes 설정값으로 docker-entrypoint.initdb.d에 볼륨을 설정하고 데이터베이스 스키마를 초기화하는 SQL 스크립트를 넣으면 컨테이너 실행시 자동으로 스키마를 생성합니다.
- 그러나 이러한 스키마 초기화가 안되는 문제가 발생하였습니다.

### 원인
- 이전에 사용한 동일한 경로의 볼륨을 clean하지 않고 그대로 사용하여 이전 프로젝트에서 사용한 볼륨의 데이터를 그대로 사용했기 때문입니다.

### 해결방법
- 사용하지 않은 볼륨을 전부 제거하고 다시 github action하여 ci/cd를 수행합니다.

```shell
$ docker volume prune
```
